# simple labels

ci:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/**'
    - '.github/actions/**'

configuration:
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.Configurations/Configurations/**'
    - 'OpenTabletDriver.Configurations/Parsers/**'

console:
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.Console/**'

core:
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver/**'

daemon:
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.Daemon/**'

desktop:
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.Desktop/**'

documentation:
- changed-files:
  - any-glob-to-any-file:
    - 'docs/**'
    - 'README.md'

gui:
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.UX/**'
    - 'OpenTabletDriver.UX.Gtk/**'
    - 'OpenTabletDriver.UX.MacOS/**'
    - 'OpenTabletDriver.UX.Wpf/**'

meta:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
      - '*'
      - 'OpenTabletDriver.Benchmarks/**'
    - all-globs-to-all-files:
      - '!.github/workflows'
      - '!.github/actions'
      - '!README.md'
      - '!TABLETS.md'
      - '!build.sh'

packaging:
- changed-files:
  - any-glob-to-any-file:
    - 'eng/**'
    - 'build.sh'
    - 'build.ps1'

plugins:
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.Plugin/**'

tests:
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.Tests/**'
    - 'tests/**'

# complex labels

'linux/gtk':
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.Native/Linux/**'
    - 'OpenTabletDriver.UX.Gtk/**'
    - 'generate-rules.sh'
    - '**/*Linux*' # TODO: verify that this works 1/3

'windows/wpf':
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.Native/Windows/**'
    - 'OpenTabletDriver/Devices/WinUSB/**'
    - 'OpenTabletDriver.UX.Wpf/**'
    - '**/*Windows*' # TODO: verify that this works 2/3
    - 'build.ps1'

macos:
- changed-files:
  - any-glob-to-any-file:
    - 'OpenTabletDriver.Native/OSX/**'
    - 'OpenTabletDriver.UX.MacOS/**'
    - '**/*MacOS*' # TODO: verify that this works 3/3
