.TH OpenTabletDriver 8

.SH NAME
opentabletdriver \- Cross platform, user mode FOSS tablet driver.

.SY
.SH SYNOPSIS

.B opentabletdriver
.RB [OPTIONS]

.YS

.SH DESCRIPTION

OpenTabletDriver is a cross platform, open source, user mode graphics
tablet driver aiming for the highest compatibility in an easily
configurable graphical user interface.

.SH OPTIONS


.SS Daemon Options

(Relevant to the portable tarball installation - OpenTabletDriver daemon when
installed via package manager is launched by systemd or equivalent)

.OP "-a, --appdata <directory>"

Manually specify application data directory, defaults to
~/.config/OpenTabletDriver/

.OP "-c, --config <directory>"

Manually specify configuration directory (location of JSON files used
to recognize tablets)

.OP "--version"

Show version information

.OP "-?, -h, --help"

Show help and usage information

.SS Graphical Front-end Options

(Relevant to the package manager installation, opentabletdriver
command will take these arguments for manipulating the GUI)

.OP "-m, --minimized"

Start OpenTabletDriver minimized, if possible in the desktop environment installed

.OP "--version"

Show version information

.OP "-?, -h, --help"

Show help and usage information for the GUI


.SH DIAGNOSTICS

The daemon log is created in the application data directory, at

~/.config/OpenTabletDriver/Logs/

by default.

The file format is almost JSON, with an end-of-array marker missing.

This can be alleviated by appending a square bracket end ']' to the end of the file.

.SH FREQUENT ISSUES AND QUESTIONS

.SS Failed to open device streams

This occurs due to a lack of permissions to open a device stream. It
is resolved by creating udev rules that give these permissions. If you
installed OpenTabletDriver via your package manager, you may need to
run the following command, and then replug your tablet.

.EX
sudo udevadm control --reload-rules
.EE

.SS Poor performance with NVIDIA

Disable "Force full composition pipeline" in the NVIDIA settings panel.


.SS Failed to initialize virtual device

.B EACCESS

Run the following command:

.EX
sudo chmod 0666 /dev/uinput
.EE

.B ENODEV

Rebooting is the only option here. Your kernel was very likely
updated, or some component of uinput was modified which requires a
reboot to resolve.
