name: 'OpenTabletDriver distro-specific Linux build'
description: 'Builds OpenTabletDriver for a specific Linux distribution and publishes the relevant artifact'
inputs:
  runtime:
    description: '.NET runtime target (e.g. win-x64 linux-arm64)'
    required: true
  package-name:
    description: 'The --package argument for package.sh'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install required packages for Debian
      if: inputs.package-name == 'Debian'
      shell: bash
      run: sudo apt update && sudo apt install -y debhelper dotnet-sdk-8.0 build-essential

    - name: Install required packages for RedHat/Fedora
      if: inputs.package-name == 'RedHat'
      shell: bash
      run: sudo dnf install -y rpm-build systemd-rpm-macros libicu openssl-libs zlib krb5-libs dotnet-sdk-8.0 tree jq

    # re-checkout repository prior to build to ensure git root is initialized (causes OpenTabletDriver#3774 if not done)
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # we need tags _and_ history for correct VERSION_SUFFIX'ing

    - name: ${{ inputs.package-name }} ${{ inputs.runtime }} Publish
      id: build
      shell: bash
      run: ./eng/bash/package.sh --package ${{ inputs.package-name }} --ci -r ${{ inputs.runtime }} --output build-${{ inputs.package-name }}
      # should output the following keys to GITHUB_OUTPUT:
      #  - output-file: artifact name
      #  - output-file-display-name: artifact display name
      #  - version: OpenTabletDriver version
      # TODO: version return value unused, not sure where to use?

    - name: ${{ inputs.package-name }} ${{ inputs.runtime }} Artifact upload
      uses: ./.github/actions/handle-artifact
      with:
        file-display-name: ${{ steps.build.outputs.output-file-display-name }}
        files: build-${{ inputs.package-name }}/${{ steps.build.outputs.output-file }}
