blank_issues_enabled: true
contact_links:
  - name: OpenTabletDriver Discord Guild
    url: https://opentabletdriver.github.io/Discord
    about: You may also wish to seek assistance through our Discord guild
