name: Feature Request
description: Create a feature request to help add more to OpenTabletDriver
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Fill out the fields below adequately so that we have an easier time responding to your request. Thank you.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        List what you would like to see added or changed.
        Be descriptive and use images or video when possible.
      placeholder: ex. I would like a new feature such that...
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: |
        Please make sure you are able to tick the items below, so that all parties involved have an easier time.
        Your issue is very likely to be closed and ignored if these conditions are not met.
      options:
        - label: I have searched the existing issues and this new issue is not a duplicate of any.
          required: true
        - label: I have written a concise and meaningful title.
          required: true
        - label: I am on the latest version of OpenTabletDriver.
          required: false
