name: Configuration Request
title: "Add support for "
description: Request for a new tablet device to be supported
labels: ["configuration"]
body:
  - type: markdown
    attributes:
      value: |
        The information below can mostly be found on the product page.
        Please try to fill out as many of the details as you can.

  - type: input
    id: manufacturer
    attributes:
      label: Manufacturer
      placeholder: ex. Wacom
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Product Name
      placeholder: ex. CTL-472
    validations:
      required: true

  - type: input
    id: width
    attributes:
      label: Device Width
      placeholder: ex. 294mm
    validations:
      required: false

  - type: input
    id: height
    attributes:
      label: Device Height
      placeholder: ex. 166mm
    validations:
      required: false

  - type: input
    id: pressure
    attributes:
      label: Pressure Levels
      placeholder: ex. 8192
    validations:
      required: false

  - type: input
    id: lpi
    attributes:
      label: Lines per Inch (LPI)
      placeholder: ex. 5080
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Anything else you would like to add?
    validations:
      required: false

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostic Information
      description: |
        Export diagnostics through the OpenTabletDriver GUI from menu <kbd>Help</kbd> → <kbd>Export Diagnostics</kbd>.
        Then, in the text area below, either attach the file\* or paste its contents\*\*.

        \*: You may need to rename the file to have a `.txt` extension for GitHub to allow uploading it.
        \*\*: If pasting contents, it would be helpful to use a JSON code block, as you can see in the placeholder text below.
      placeholder: |
        ```json
        <paste file contents>
        ```
        (Notice the triple backticks)
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: |
        Please make sure you are able to tick the items below, so that all parties involved have an easier time.
        Your issue is very likely to be closed and ignored if these conditions are not met.
      options:
        - label: I have searched the existing issues and this new issue is not a duplicate of any.
          required: true
        - label: I have written a concise and meaningful title.
          required: true
