name: 'OpenTabletDriver Build Wrapper'
description: 'Runs the appropriate build based on properties'
inputs:
  runtime:
    description: '.NET runtime target (e.g. win-x64 linux-arm64)'
    required: true
  package-name:
    description: 'Package name, --package argument for package.sh'
    required: true
  container:
    description: 'Set to anything to apply container workarounds'
  signed:
    description: 'Whether the package should be signed'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: ./.github/actions/setup-dotnet

    # containers need safe.directory: https://github.com/actions/checkout/issues/1169
    - name: "Fix container git permissions"
      if: inputs.container
      shell: bash
      run: |
        if [ z${{ inputs.container }} == 'zfedora' ]; then
          sudo dnf install -y git
        fi
        hash git &>/dev/null && \
          git config --system --add safe.directory /__w/OpenTabletDriver/OpenTabletDriver

    - name: "Fetch latest rcodesign version (macOS builds)"
      id: rcodesign-version
      if: inputs.runtime == 'osx-arm64' && inputs.signed == 'true'
      shell: bash
      # crates.io API requires a user agent and recommends providing a way of contact
      # https://crates.io/data-access#api
      run: |
        echo "version=$(curl -s https://crates.io/api/v1/crates/apple-codesign -H 'User-Agent: https://github.com/OpenTabletDriver/OpenTabletDriver' | jq -r '.crate.max_version')" >> "$GITHUB_OUTPUT"

    - name: "Cache rcodesign (macOS builds)"
      if: inputs.runtime == 'osx-arm64' && inputs.signed == 'true'
      id: cache-rcodesign
      uses: actions/cache@v5
      with:
        path: ~/.cargo/bin/rcodesign
        key: ${{ inputs.runtime }}-rcodesign-${{ steps.rcodesign-version.outputs.version }}

    - name: "Install rcodesign (macOS builds)"
      if: steps.cache-rcodesign.outputs.cache-hit != 'true' && inputs.runtime == 'osx-arm64' && inputs.signed == 'true'
      shell: bash
      run: cargo install apple-codesign

    - name: "BASH Build Artifact"
      uses: ./.github/actions/build-bash
      with:
        runtime: ${{ inputs.runtime }}
        package-name: ${{ inputs.package-name }}
        signed: ${{ inputs.signed }}
