#!/bin/bash

BOLD_YELLOW='\033[1;33m'
RESET='\033[0m'

set -e

if [ "$1" = "configure" ]; then
     if lsmod | grep hid_uclogic > /dev/null; then
          rmmod hid_uclogic || true
     fi

     if lsmod | grep wacom > /dev/null; then
          rmmod wacom || true
     fi

     if udevadm control --reload-rules; then
          udevadm trigger --settle || true
          udevadm trigger --name-match=uinput --settle || true
     fi

     echo -e "${BOLD_YELLOW}Run the daemon by invoking \`otd-daemon\`, or by enabling opentabletdriver.service${RESET}"
fi
