.TH OpenTabletDriver (8)

.Sh NAME

.B opentabletdriver

Open source, cross platform, user mode tablet driver.

.SY
.SH SYNOPSIS

.B opentabletdriver
.RB [OPTIONS]

.YS

.SH DESCRIPTION

The goal of OpenTabletDriver is to be cross platform as possible with
the highest compatibility in an easily configurable graphical user
interface.

.SH OPTIONS

.SH DIAGNOSTICS
