name: 'Setup .NET'
description: 'Sets up .NET with the preferred OpenTabletDriver defaults'
inputs:
  dotnet-version:
    description: "The .NET version to use. See actions/setup-dotnet"
    default: '8.0'
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        cache: true
        cache-dependency-path:
          - '**/packages.lock.json'
          - 'Directory.Build.props'
